/*************************************************************************
*  Object Name: constants.ts
**************************************************************************
*  Revision History:
**************************************************************************/

export class CONSTANTS {


    static readonly CHART_OF_ACCOUNT_TYPES = {
        TAX: "ACCTAX",
        ASSET: "ASSET",
        BUSINESS : "BUSNSS",
        CAPITAL : "CAPITA",
        EQUITY : "EQUIT",
        EXCLUDABLE_REPORTABLE: "EXCRPT",
        EXCLUDABLE_NON_REPORTABLE: "EXNRPT",
        EXPENSE: "EXPENS",
        INCOME: "INCOME",
        LIABILITY: "LIABIL",
        NON_POSTING: "NONPOS",
        NON_TAXABLE_DEDUCTIBLE: "NTXDED",
        PAYROLL_CODE: "PAYCOD",
        TAX_ASSIST: "TAXAST",
        TAXABLE_DEDUCTIBLE: "TAXDED",
        TAXABLE_NON_DEDUCTIBLE: "TAXNDD"
    }

    static readonly CODE_TYPES = {
        ACCOMODATIONS: 'ACCCOS',
        ACCOUNTINGROLE: 'ACCROL',
        ACCOUNTING_DAY_OF_THE_MONTH: 'ACTRUL',
        ACCOUNT_TYPE: 'ACCTYP',
        ACCOUNT_TYPES2: 'ACCOUN',
        ACCOUNT_TYPES: 'ACTYPE',
        ACQUISITION_TYPE: 'BUYTYP',
        ACQUISITION_TYPES: 'ACQTYP',
        ACTION_PRIORITY: 'PRIORI',
        ACTION_REPEAT_DURATION_TYPE: 'REPDUR',
        ACTION_SEND_CONTROL: 'SQLSND',
        ACTION_SEND_RECIPIENT_TYPE: 'SNDCLS',
        ACTION_STATUS: 'ACSTAT',
        ACTION_TRIGGER_TYPE__OBSOLETE_: 'TRGTYP',
        ACTION_TYPE: 'ACTTYP',
        ADDRESS_PART: 'ADRPRT',
        ADDRESS_TYPE: 'ADDTYP',
        ADULT_GUEST_COUNT: 'ADLGST',
        AGE_RANGES: 'AGES  ',
        AIR_TRANSPORTATION_CLASS: 'AIRCLA',
        ALERT_NOTIFICATION: 'ALERT ',
        ALL_FILE_PHONES_IN_EMAIL: 'CUSEML',
        APOPUP: 'APOPUP',
        AP_BILLING_POINT: 'APBILL',
        ASSIGNEE_TYPES: 'ASTYPE',
        ASSIGNMENT_TYPES: 'ASNTYP',
        BASEMENT_TYPE: 'BASMNT',
        BASIC_STATUS: 'STATUS',
        BATHROOM_COUNT: 'BATHRM',
        BEDROOM_COUNT: 'BEDRM ',
        BILLING_ADVANCE_STATUS: 'ADVSTA',
        BILLING_STATUS: 'BILSTA',
        BILL_TO_TYPES: 'BILLTO',
        BILL_TYPE: 'BILTYP',
        BMA_CLASS: 'BMACLS',
        BMA_TYPES: 'BMATYP',
        BMA_TYPES__BMA_BPO_: 'BMAMET',
        BRANCHES: 'BRANCH',
        BRANCHES_OF_G_L_ACCOUNT: 'CKREQ ',
        BUDGET_AMOUNT_TYPES: 'BDGAMT',
        BUDGET_GROSSUP: 'BDGGUP',
        BUDGET_LIMIT_TYPES: 'LIMIT ',
        BUDGET_TIERS: 'BDGTIE',
        BUDGET_TYPE: 'BDGTYP',
        CALCULATION_TYPE: 'TRANS ',
        CAPTYP: 'CAPTYP',
        CAR_SPACES_COUNT: 'CARPAR',
        CASH_RECEIPT_ACCOUNT: 'CASHAC',
        CASH_RECEIPT_REVERSAL_ACCOUNT: 'REVAC ',
        CHART_OF_ACCOUNT_TYPES: 'COATYP',
        CHILD_GUEST_COUNT: 'CHLGST',
        CODE_TYPES: 'CODTYP',
        COLLECTION_LOCATIONS: 'COLLEC',
        COMBINED_EVENT_TRIGGER_COMPARITOR: 'TRCOND',
        COMPENSATION_WORKSHEET_STATUS: "CMPWSS",
        CONFLG: 'CONFLG',
        CONTACT_ASSIGNMENT_RULES_RESULTS_LIMIT: 'SELLIM',
        CONTACT_TYPE: 'CONTYP',
        CONTAINER_TYPES: 'CONTAI',
        CONTROL_TYPE: 'CTLTYP',
        COST_TYPES: 'COSTYP',
        COUNTRY_CODES__ISO_: 'COUNTR',
        COUNTRY_CURRENCY_TYPE: 'COUCUR',
        COVERAGE_TYPES: 'COVTYP',
        CREDIT_REASON: 'CRREAS',
        CREDIT_STATUS_TYPE: 'CREDIT',
        CURRENCY_TYPE: 'CURNCY',
        CUSTOMER_SOURCE: 'CUSSRC',
        CUSTOM_CODE_TYPE: 'CUSTCD',
        CURRENCY_SOURCE: "CURSRC",
        CUSTOM_FIELD_DEFAULT_FROM_SOURCE_CONTROL: 'DEFSRC',
        CUSTOM_FIELD_DISPLAY_TYPE: 'DISPLA',
        CUSTOM_FIELD_INPUT_LOCATION: 'INPLOC',
        CUSTOM_FIELD_SCREEN_TYPE: 'SCREEN',
        CUSTOM_FIELD_SEARCH_OR_INPUT_ONLY_INDICATOR: 'USAGE ',
        DATA_DICTIONARY_INPUT_TYPE: 'DDINPU',
        DATA_DICTIONARY_STATUS: 'DDSTAT',
        DATA_DICTIONARY_TYPE: 'DDTYPE',
        DATE_RELEVANCE_CLASSIFICATION_ON__OR_AROUND: 'AROUND',
        DEED_STATUS: 'DEEDRE',
        DEED_TYPES: 'DEETYP',
        DEFAULT_EMAIL_STYLE: 'DEFSTY',
        DEFAULT_FROM_EMAIL_ADDRESS: 'DEFEML',
        DEFAULT_PRIMARY_RESOURCE_ROLE: 'DSTROL',
        DELIMITER_TYPES: 'DELTYP',
        DELIVERY_METHOD: 'DELIME',
        DERIVATION: 'DERIVA',
        DESCRIPTIONS_FOR_SYSCON_PARAMETERS: 'CODHLP',
        DESIGNATIONS: 'DESIGN',
        DIRECTION_TYPE: 'DIRECT',
        DISBURSEMENT_TYPE: 'DISBUR',
        DISTRIBUTION_TYPE: 'DIST  ',
        DOCUMENT_TYPE: 'DOCTYP',
        EMAIL_ACCESS_EXPIRATION: 'EXPIRE',
        EQUITY_TYPES: 'EQUTYP',
        EVENT_TRIGGER_BEFORE_AFTER: 'TRGDEL',
        EVENT_TYPE: 'TRGCLS',
        EXCEPTION_REASON: 'EXCREA',
        EXPENSE_CATEGORIES: 'EXPCAT',
        EXPENSE_DECLINED_REASONS: 'EXPDRE',
        EXPENSE_MANAGEMENT_REPORT_TYPE: 'EXRPTY',
        EXPENSE_REPORT_STATUS: "EXREST",
        EXPENSE_LINE_STATUS: "EXPSTA",
        EXPENSE_TYPES: 'EXPTYP',
        EXTERIOR_SIDING_TYPE: 'SIDTYP',
        EXTERNAL_SERVER_ADDRESS: 'EXTSRV',
        FACILI: 'FACILI',
        FAX_ADDRESS_PREFIX: 'FAXPRE',
        FAX_ADDRESS_SUFFIX: 'FAXSUF',
        FAX_NUMBER_IN_TO: 'FAXNIT',
        FAX_RESOURCE_ADDRESS: 'FAXIP ',
        FAX_SERVER_ADDRESS: 'FAXADD',
        FEE_BASIS_: 'BASIS ',
        FEE_CLASS: 'FEECLS',
        FEE_TYPE: 'FEETYP',
        FILES_FILE_NUMBER_TYPE: 'CUSNBR',
        FILES_PHONE_TYPE: 'CUSPHN',
        FILES_STATUS: 'CUSSTA',
        FILES_STATUS_FOR_FINANCIAL_SCHEDULE_EVENTS: 'CUSST2',
        FILES_TYPE: 'CUSTYP',
        FILE_LIBRARY_TYPES: 'FLIB  ',
        FILE_MANAGER: 'POC   ',
        FILE_NUMBER_CONFIGURATION: 'FILNUM',
        FINANCE_TRANSFER_SOURCE_TYPE: 'SRCTYP',
        FINANCE_TRANSFER_STATUS: 'TRNSTA',
        FINANCIAL_TRANSACTION_TYPE: 'FNTTYP',
        FINANCIAL_YEAR: 'YERTYP',
        FINANCING_TYPE: 'FINTYP',
        FOLDER_DEFAULT_INVOICE_FORM_TYPE: 'FOLINV',
        FOLLOW_UP_NOTIFICATION: 'FOLLOW',
        FORM_ACCESS: 'FRMACC',
        FORM_STATUS: 'FRSTAT',
        FORM_UPDATE_NOTIFICATION: 'FRMNOT',
        FUND_SOURCE_TYPES: 'FUNSRC',
        FUND_TRANSFER_TYPE: 'FTRTYP',
        FUND_TYPE: 'FUNMTD',
        GARAGE_TYPE: 'GARAGE',
        GENDER_TYPE: 'GENDER',
        HOA_MEMBERSHIP: 'HOAMEM',
        HOME_AGE: 'HOMAGE',
        HOME_CLEANING_TYPES: 'HOUCLE',
        HOME_GARAGE_TYPES: 'HOUGAR',
        HOME_HEATING_TYPES: 'HEAT  ',
        HOME_OWNERSHIP_STATUS: 'HOMSTA',
        HOME_STYLE_TYPES: 'HOMSTY',
        HOME_TYPES: 'HOMTYP',
        HOTEL_ROOM_TYPES: 'ROOMST',
        HOUSE_LISTING_STATUS: 'HSTAT ',
        HOUSE_PET_TYPES: 'HOUPET',
        HOUSING_PROPERTY_TYPE: 'PROPTY',
        HOUSING_TYPE: 'HOUPRO',
        INPUT_TYPES: 'INPTYP',
        INPUT_VALIDATORS: 'INPVLD',
        INSPECTION_TYPES: 'INSTYP',
        INTEREST_ACCOUNT_TYPE: 'INACTY',
        INTEREST_BASIS_TYPES_: 'INTBAS',
        INTEREST_ENDING_CALULCATION_METHOD: 'INTEND',
        INTEREST_PAYMENT_METHOD: 'INTPAY',
        INTEREST_TYPE: 'INTTYP',
        INTERNAL_SERVER_ADDRESS: 'INTSRV',
        INVOICE_OFFSET_METHOD: 'OFFMET',
        INVOICE_STATUS: 'INVSTA',
        INVOICE_TYPE: 'INVTYP',
        KEY_FIELD_NUMERIC_EVENT_COMPARISON_CODE: 'TRGCOM',
        KEY_FIELD_NUMERIC_EVENT_VARIANCE_CODE: 'TRGCM2',
        LAHA__: 'LAHA  ',
        LANGUAGE: 'LANGUA',
        LEASE_DURATION_TYPES: 'LEASE ',
        LEASE_STATUS_TYPES: 'LEASTA',
        LENGTH_OF_TERM: 'DIPLO ',
        LENGTH_OF_TERMS: 'LSTERM',
        LENGTH_OF_TERMS_MONTHS_AND_YEARS_: 'LTERM ',
        LISTED_WITH_OTHER_BROKER_FSBO: 'LISTWI',
        LOCAL_SERVER_EMAIL: 'EMLDOM',
        LOGO_TYPE_SETTINGS_FOR_EXTERNAL_VIEWS: 'VWLOGO',
        LOT_SIZE_TYPE__GENERAL_: 'LOTSZ ',
        LOT_SIZE_TYPE__SPECIFIC_: 'LOTSIZ',
        MARITAL_STATUS: 'MARITA',
        MARKETING_TIME: 'MKTTIM',
        MASTER_FIELD: 'FLDCOD',
        MASTER_FIELD_CATEGORY: 'MFLCAT',
        MASTER_TEAM_INDICATOR: 'MASTER',
        MORTGAGE_PAYMENT_SCHEDULE_TYPES: 'MORSCH',
        MORTGAGE_TYPES: 'MORTYP',
        MOVE_TYPE: 'MOVTYP',
        NAME_IN_SUBJECT: 'SBJCUS',
        NEIGHBORHOOD_TYPES: 'NEIGHB',
        NOTES_IN_EMAIL: 'EMLNOT',
        NOTE_CLASS: 'NOTECL',
        NOTE_NOTIFICATION__EXTERNAL_: 'NOTE  ',
        NOTE_NOTIFICATION__INTERNAL_: 'CLINOT',
        NOTE_TYPE: 'NOTTYP',
        NUMBER_OF_BATHROOMS: 'HCNT  ',
        NUMBER_OF_BEDROOMS: 'INTNUM',
        NUMBER_OF_BUSINESS_DAYS: 'NOTPED',
        NUMBER_OF_DEPENDENTS: 'CNTDEP',
        NUMBER_OF_PETS: 'PETS  ',
        NUMERIC_REPRESENTATION_OF_COUNTRIES_USED_BY_WINDOWS: 'LCID  ',
        OCCUPANT_TYPES: 'OCCTYP',
        OFFER_COUNT: 'OFFERS',
        OFFER_STATUS_TYPES: 'OFFSTA',
        ON_HOLD_REASONS: 'ONHOLD',
        ORGANIZATION_LEVEL_TYPES: 'ORGLEV',
        ORGANIZATION_TYPE: 'ORGTYP',
        PAID_PAYMENT_NOTIFICATIONS: 'PAYNOT',
        PASSWORD_POLICIES: 'PWDPOL',
        PAYMENT_BATCH_STATUS: 'PAYSTA',
        PAYMENT_CODE: 'PAYCOD',
        PAYMENT_REIMBURSABILITY_TYPES: 'PAYTYP',
        PAYMENT_SCHEDULING_TYPES: 'PAYSCH',
        PAYMENT_STATUS: 'PAYMST',
        PAYMENT_TERM_TYPES: 'PAYTER',
        PAYMENT_TYPE: 'PAYMET',
        PAYROLL_ADJUSTMENT_TYPE: 'PAYADJ',
        PAYROLL_CODE_CATEGORY: 'PAYCAT',
        PERIOD_TYPE: 'PERTYP',
        PET_TYPES: 'PET   ',
        PREFERRED_CONTACT_METHOD_TYPES: 'PFDCM ',
        PROCESS_DEFINITION_TYPE: 'PROTYP',
        PROCESS_STATUS_CODE: 'XSTATU',
        PROGRAM_PAYMENT_STATUS: 'PPDSTS',
        PROGRAM_STATUS: 'PROSTA',
        PROGRAM_STATUS_FOR_FINANCIAL_EVENTS: 'PROST2',
        PROGRAM_TYPE: 'SVPLAN',
        PROGRAM_TYPES: 'PROGRA',
        PROPERTY_STATUS: 'PPERTY',
        PROPERTY_TYPE: 'PROSTL',
        PROPERTY_TYPES: 'PROPER',
        PROVIDER_TYPE: 'PROVID',
        PURCHASE_THROUGH_TYPE: 'PURTHR',
        PURPOSE_OF_LOAN: 'LNPRPS',
        RATE_BASIS: 'RATE  ',
        RATINGS: 'RATING',
        RECEIPT_NOTIFICATION: 'RCPNOT',
        REFERRAL_REASONS: 'REFREA',
        REFERRAL_STATUS: 'REFSTA',
        REFERRAL_TYPE: 'REFTYP',
        REJECTION_REASON: 'DODRJR',
        RELOCATION_TYPE: 'RELOTY',
        REMOVAL_INSURANCE_TYPE: 'REMSUR',
        RENTER_TYPE: 'RNTBND',
        REPAIR_TYPE: 'REPTYP',
        REPORTING_CATEGORIES: 'REPCAT',
        REPORT_CATEGORY: 'RPTCAT',
        REQUIRE_LOGIN_FROM_EMAIL_LINK: 'LOGIN ',
        REQUISITION_TYPES: 'REQTYP',
        ROLE_SECURITY_LEVEL: 'ROLLEV',
        ROLE_SPECIAL_FLAG: 'ROLFLG',
        SALUTATION_TYPES: 'SALUTA',
        SEARCH_OPERATORS: 'JOIN  ',
        SECURE_SERVICENGINE: 'USESSL',
        SERVICENGINE_MAILING_EMAIL_PARAMETERS: 'V2MAIL',
        SERVICE_BUNDLE_ACCOUNT: 'BNDACC',
        SERVICE_BUTTON_STATUS_IMAGE_XREF: 'BUSTAT',
        SERVICE_MANAGER: 'SPOC  ',
        SERVICE_NAME: 'SVCTYP',
        SERVICE_STATUS_CODE: 'PROTXT',
        SERVICE_STATUS__CORE_: 'SVSTAT',
        SERVICE_TYPE: 'SVCCOD',
        SERVICING_TEAM: 'TEAM  ',
        SEWAGE_DISPOSAL_TYPES: 'SEWER ',
        SHIPMENT_METHOD: 'SHIMET',
        SIM_EXPORT_FILE_DELIMITER_TYPE: 'DELIMT',
        SIM_FILE_FORMAT: 'SIMFMT',
        SIM_NATCH_STATUS: 'SIMSTS',
        SIM_PROCESS_DEFINITION_TYPE: 'SIMPDT',
        SPREADSHEETS_NOT_USED: 'XLFORM',
        SQUARE_FOOTAGE_RANGE: 'SQRFT ',
        STATUS_CHANGE__ACCEPTANCE__NOTIFICATION: 'STACHG',
        STATUS_CHANGE__CANCEL__NOTIFICATION: 'STACH3',
        STATUS_CHANGE__COMPLETED__NOTIFICATION: 'STACH4',
        STATUS_CHANGE__DECLINED__NOTIFICATION: 'STACH2',
        STATUS_CHANGE__FINAL__NOTIFICATION: 'STACH5',
        STATUS_CHANGE__STARTED__NOTIFICATION: 'STACH1',
        SYSCON_SETTINGS: 'SYSCFG',
        TAXABILITY_STATUS: 'TAXSTA',
        TAX_FILING_CLASSIFICATIONS: 'TAXFIL',
        TAX_FREQUENCY_CLASSIFICAITONS: 'TXFREQ',
        TAX_MEMO_STATUS: 'TXMSTA',
        TAX_MEMO_STATUS_REASON: 'TXMSTR',
        TAX_TYPES: 'TAXTYP',
        TEACTR: 'TEACTR',
        TELEPHONE_CONNECTINO_TYPES: 'TELEPH',
        TIME_INTERVAL: 'PRXTIM',
        TO_CONTACT_INFORMATION: 'TOINFO',
        TPOC_ROLE: 'TPOC  ',
        TRANSPORTATION_TYPE: 'PRETRN',
        TRIP_TYPE: 'TRITYP',
        TYPE_OF_REQUEST: 'EQRQTP',
        UNALLOWABLE_REASON_CODE: 'UNALOW',
        USER_TYPES: 'USRTYP',
        USE_CDO: 'CDONTS',
        VARIABLE_PERCENTAGE_RATE: 'VARPCT',
        VIEW_TYPES: 'VIEW  ',
        WATER_SUPPLY_TYPES: 'WATER ',
        WEB_SERVER_IP: 'WEB_IP',
        WIRE_INSTRUCTION_TYPE: 'WINTYP',
        YEARS_OWNED_PROPERTY: 'YRSOWN',
        YES_OR_NO: 'YESNO '

    }

    static readonly FORM_KEY_FIELD = {
        HIGHLIGHT_COLOR : '#FFFF00',
        CURRENCY_COLOR : '#00FF00'
    }

    static readonly ASSIGNEE_TYPE = {
        CONTACT: 'CON',
        CUSTOMER: 'CUS',
        ORGANIZATION: 'ORG'
    }
    static readonly EXPENSE_MANAGEMENT_REPORT_TYPE = {
        CODE_TYPE: CONSTANTS.CODE_TYPES.EXPENSE_MANAGEMENT_REPORT_TYPE,

        CUSTOMER: 'CUSTOM',
        SUPPLIER: 'SUPPLR',
        ALL: 'ALL'
    }

    static readonly EM_CURRENCY_EXCHANGE_OPTIONS = {
        EMCREX: 'EMCREX',
        LINE: 'LINE',
        NONE: 'NONE',
        REPORT: 'REPORT'
    }

    static readonly EM_SUPPORTING_DOCUMENTATION = {
        CODE_TYPE: 'SUPDOC',
        LINE_DOC_REQUIRED_OVER_AMOUNT: 'LINAMT',
        LINE_DOC_REQUIRED: 'LINDOC',
        NO_DOCS_REQUIRED: 'NODOCS',
        REPORT_DOC_REQUIRED: 'REPDOC'
    }

    static readonly FINANCIAL_TRANSACTION_TYPE = {
        CODE_TYPE: CONSTANTS.CODE_TYPES.FINANCIAL_TRANSACTION_TYPE,

        FEE: 'FEE',
        GROSSUP: 'GRSSUP',
        INTEREST_ACCRUAL: 'INTACR',
        JOURNAL_ENTRY: 'JRNLEN',
        PAYMENT: 'PAYMNT',
        PAYROLL_TRANSACTION: 'PAYTRN'

    }
    static readonly EXPENSE_LINE_STATUS = {
        CODE_TYPE: CONSTANTS.CODE_TYPES.EXPENSE_LINE_STATUS,

        APPROVED: 'APPROV',
        DECLINED: 'DECLIN',
        NEW: 'NEW',
        PAID: 'PAID',
        REVIEWED: 'REVIEW',
        SUBMITTED: 'SUBMIT'
    }

    static readonly EXPENSE_REPORT_STATUS = {
        CODE_TYPE: CONSTANTS.CODE_TYPES.EXPENSE_REPORT_STATUS,

        APPROVED: 'APPROV',
        PROCESSED: 'COMPLE',
        DECLINED: 'DECLIN',
        ON_HOLD: 'ONHOLD',
        PAID: 'PAID',
        NEW: 'PENDIN',
        PARTIAL_PAID: 'PRPAID',
        RECALLED: 'RECALL',
        REVIEWED: 'REVIEW',
        SAVED: 'SAVED',
        SUBMITTED: 'SUBMIT'
    }

    static readonly GRANT_TYPE = {
        DEFAULT: 'DEFAULT',
        CLASS_SUBCLASS: 'CLASS_SUBCLASS',
        ORGANIZATION_CLASS: 'ORG_CLASS'
    }
    static readonly INPUT_VALIDATORS =
        {
            CURRENCY: 'CURNCY',
            DATE: 'DATE',
            NUMBER: 'NUMBER',
            NUMBER_AS_TEXT: 'NUMTXT',
            PERCENT: 'PERCNT',
            TEXT: 'TEXT'
        };

    static readonly PERMISSION_CODES = {
        CREATE: 'CREATE',
        DELETE: 'DELETE',
        EXECUTE: 'EXECUTE',
        PRINT: 'PRINT',
        READ: 'READ',
        UPDATE: 'UPDATE',
        BUSINESS_ADMINISTRATION: 'ADMIN',
        TECHNICAL_ADMINISTRATION: 'ADMIN'
    };

    static readonly SECTION_FUNCTIONS = {
        NOTE: 'NTE'
    }


    static readonly GRANT_OBJECTS = {

        CUSTOMER_ACTION: 'CUS.ACT',
        WORKFLOW_FORM: 'CUS.ACT',

        CUSTOMER_WIRE_ACCOUNT: 'CUS.WIREAC',
        CUSTOMER_WIRE_ACCOUNT_ADD: 'CUS.WACADD',
        CUSTOMER_EXPENSE_MANAGEMENT: 'CUS.EXP',
        CUSTOMER_BUDGET_ELEMENTS: 'CUS.PRO.CTL',
        CUSTOMER_COST_ANALYSIS: 'CUS.COSTAN',
        CUSTOMER_COMPENSATION_WORKSHEET: 'CUS.CMP.WKS',
        CUSTOMER_COMPENSATION_PROFILE: 'CUS.CMP.PRF',
        CUSTOMER_COMPENSATION_ACCUMULATION_TRACKER: 'CUS.CMP.ACV',
        CUSTOMER_SALARY_AND_PAYROLL: 'CUS.FINPRO', //Not segmented, i.e. not CUS.FIN.PRO
        CUSTOMER_SHADOW_PAYROLL: 'CUS.SHDWPR',
        CUSTOMER_COST_PROJECTION: 'CUS.CPR.WKS',



        FINANCE_MATRIX_CALCULATIONS: 'BILL.MXCALC',
        FINANCE_ORGANIZATION_PAYROLL: 'BILL.CMP.WKS',

        SUPPLIER_RATES: 'SPLRAT',
        SUPPLIER_EXPENSE_MANAGEMENT: 'EMSPLR',

        EXPENSE_MANAGEMENT: 'EXPMNG',

        ORGANIZATION_WIRE_ACCOUNT: 'FINPAY',
        ORGANIZATION_COST_ANALYSIS: 'COSTAN',
        ORGANIZATION_BUDGET_TEMPLATE: 'PRO',
        ORGANIZATION_PROFILE: 'FILE',
        ORGANIZATION_EXPENSE_CONFIG : 'EXP.CFG',


        ORGANIZATIONS: {
            COMPENSATION_MASS_UPDATE: 'CMP.MUP',
            COMPENSATION_CONFIG: 'CMP.TMP',
            COMPENSATION_ACCUMULATION_CONFIG: 'CMP.ATM',
            ORGANIZATION_ACCUMULATION_WORKSHEET_GENERATION: 'CMP.AWG',
            ORGANIZATION_ACCUMULATION_WORKSHEET_TRACKER: 'CMP.AWT',
            ORGANIZATION_ACCUMULATION_WORKSHEET_PROCESSING: 'CMP.AWT', //Change the value on this if/when the role security detail screen includes a separate setting.
            COST_PROJECTION_CONFIG: 'CPR.TMP',
            PAYROLL: 'CMP.WKS',
            GLOBAL_TAX_RULES_CONFIG: 'CPR.GTR'
        },


        SYSTEM_LEVEL: {
            BUSINESS_ADMINISTRATION: 'SYS.BUSADM',
            TECHNICAL_ADMINISTRATION: 'SYS.TECADM',

            COMPENSATION_CONFIG: 'BILL.CMP.TMP',
            COMPENSATION_ACCUMULATION_CONFIG: 'BILL.CMP.ATM',
            COST_PROJECTION_CONFIG: 'BILL.CPR.TMP',
            GLOBAL_TAX_RULES_CONFIG: 'BILL.CPR.GTR',
            PAYROLL: 'BILL.CMP.WKS',
            EXPENSE_CONFIG: 'BILL.EXP.CFG'
        }


    }


    static readonly SECURITY_ERRORS =
        {
            USER_NOT_AUTHORIZED: "USER_NOT_AUTHORIZED",
            BAD_CREDENTIALS: "BAD_CREDENTIALS",
            USER_INACTIVE: "USER_INACTIVE",
            APIKEY_INVALID: "APIKEY_INVALID",
            USERID_INVALID: "USERID_INVALID",
            APPLICATIONKEY_INVALID: "APPLICATIONKEY_INVALID",
            METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED"
        }

    static readonly ERROR_ROUTE_REDIRECTS =
    {
        USER_NOT_AUTHORIZED: "login"
    }

    static readonly CONTENT_TYPE ={
        OFFICE: 'application/octet-stream'
    }

    static readonly COMPENSATION_WORKSHEET_STATUS = {
            CODE_TYPE: CONSTANTS.CODE_TYPES.COMPENSATION_WORKSHEET_STATUS,
            PENDING : "PENDIN",
            CLOSED: "CLOSED",
            COMPLETED: "COMPLT",
            APPROVED: "APPROV",
    }

    static readonly CURRENCY_SOURCE = {
        CODE_TYPE: CONSTANTS.CODE_TYPES.CURRENCY_SOURCE,
        HOME: "HOME",
        HOST: "HOST",
        SYSTEM: "SYSTEM",
        ORGANIZATION: "ORG",
        PRIMARY_PAYROLL_SYSTEM: "PRIMAR",
        SECONDARY_PAYROLL_SYSTEM: "SECOND",
        ALTERNATE_1_PAYROLL_SYSTEM: "ALTER1",
        ALTERNATE_2_PAYROLL_SYSTEM: "ALTER2",
    }

    static readonly COMPENSATION_SUBSCRIPTION_FORMULA_PREFIX =  {
        ORC: "ORC", AIRINC: "AIRINC"
    }

    static readonly APPLICATION_ROUTES = {
        ACCOUNT: "accounts",
        NOTE: "notes",
        CUSTOMER: "customers",
        MATRIX_CALCULATION: "matrix-calculations",
        CODING_EXAMPLE: "samples",
        CODING_EDIT_EXAMPLE: "edit-sample",
        ORGANIZATION: "organizations",
        ADMINISTRATIVE: "admin",
        GADGETS: "gadgets"
    }

    static readonly REGISTER_BATCH_TYPE =
    {
        SHADOW: 1,
        COMPENSATION: 2,
    }
}
